I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 522, in script
    if attendedcollege == True:
  File "game/script.rpy", line 522, in <module>
    if attendedcollege == True:
NameError: name 'attendedcollege' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 522, in script
    if attendedcollege == True:
  File "C:\Users\Reis\Documents\The Patrician Renpy\renpy\ast.py", line 1760, in execute
    if renpy.python.py_eval(condition):
  File "C:\Users\Reis\Documents\The Patrician Renpy\renpy\python.py", line 1944, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Users\Reis\Documents\The Patrician Renpy\renpy\python.py", line 1937, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 522, in <module>
    if attendedcollege == True:
NameError: name 'attendedcollege' is not defined

Windows-8-6.2.9200
Ren'Py 7.1.1.929
Throw Me In the River 1.0
Mon Oct 29 21:04:18 2018
